module "vpc" {
	source = "./modules/vpc"
	shared_credentials_file = "/root/.aws/credentials"
	skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
	instance-tenancy = "default"
	enable-dns-support = "true"
	enable-dns-hostnames = "true"
	vpc-name = "TerraLab-vpc"
	vpc-location = "Ohio"
	region = "us-east-2"
	internet-gateway-name = "TerraLab-igw"
	map_public_ip_on_launch = "true"
	public-subnets-name = "public-subnets"
	public-subnets-location = "Ohio"
	public-subnet-routes-name = "public-subnet-routes"
	private-subnets-location-name = "Ohio"
	private-subnet-name = "private-subnets"
	total-nat-gateway-required = "1"
	eip-for-nat-gateway-name = "eip-nat-gateway"
	nat-gateway-name = "nat-gateway"
	private-route-cidr = "0.0.0.0/0"
	private-route-name = "private-route"
	vpc-cidr = "10.10.0.0/16"
	vpc-public-subnet-cidr = ["10.10.1.0/24","10.10.2.0/24"]
	vpc-private-subnet-cidr = ["10.10.3.0/24","10.10.4.0/24"]	
}